apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-acm-hardening
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: feature.open-cluster-management.io/addon-governance-policy-framework, operator: In, values: ["available"]}
